### ISSUE TITLE
Need to create Breakfast recipe

### ISSUE THREAD

**Issue by jwood77** [IntroToCode/Spring21_Recipes_Codemates14#1]
## 💬 Discussion topic: 

Need to create breakfast recipe

## ❗ Potential issues

Dividing work and choosing 1 recipe

## 👥 People to consult

@stalerat 
@cvo24 
@candiceke 
@Davidbolivarz 

## 📃 Details

Each recipe MUST have contributions from ALL members

**Comment by Davidbolivarz** [comment]
Thanks, Jordan, I suggest pancakes.

**Comment by cvo24** [comment]
I prefer eggs for breakfast.

**Comment by candiceke** [comment]
How about scrambled eggs and pancakes?

**Comment by jwood77** [comment]
Great, lets use a mix so it's easier!  I'll open a pull request
