### ISSUE TITLE
Need to create lunch recipe

### ISSUE THREAD

**Issue by cvo24** [IntroToCode/Spring21_Recipes_Codemates14#2]
## 💬 Discussion topic

Need to create a lunch recipe 

## ❗ Potential issues

Dividing work and choosing 1 recipe

## 👥 People to consult

@jwood77 
@candiceke 
@Davidbolivarz 
@joewadcan 
@stalerat 

## 📃 Details

Acceptance Criteria: Each recipe must have contributions from all members! 
Acceptance Criteria: Each recipe must clearly state all ingredients! 
Acceptance Criteria: Each recipe must clearly state time to make!

**Comment by jwood77** [comment]
Thanks!  How about fish tacos?

**Comment by Davidbolivarz** [comment]
How about shrimp instead?

**Comment by candiceke** [comment]
Can we put both in the taco?

**Comment by cvo24** [comment]
Yes, let's do it.
