### ISSUE TITLE
Ideas for dinner recipe

### ISSUE THREAD

**Issue by candiceke** [IntroToCode/Spring21_Recipes_Codemates14#3]
## 💬 Discussion topic

Let's decide on what to make for dinner

## ❗ Potential issues

Dividing work and figure out recipe for dinner

## 👥 People to consult

@cvo24 @jwood77 @Davidbolivarz 

## 📃 Details

Each recipe MUST have contributions from ALL members

Acceptance criteria: liked/approved by all members; easy to cook (can be made within an hour); easy to find the ingredients

**Comment by Davidbolivarz** [comment]
How about steak and fries?

**Comment by cvo24** [comment]
Sounds great! Let's start the recipe
